### PR TITLE
Implement base menu factory to reduce build size

### PR DESCRIPTION
**Pull request by MikeKlemarewski**
### Note:
I am not the most familiar with webpack (which I'm using to build) so if there is a way to get around the issue that this PR is trying to solve using only webpack, please let me know.

----------

We use react-burger-menu in a mobile single page app. Being a mobile app, we'd like the app size to be as small as possible, incase the user is browsing on a poor network. I was checking our app size using [webpack bundle size analyzer](https://github.com/robertknight/webpack-bundle-size-analyzer).

screen shot 2016-06-29 at 10 23 17 am

I was shocked to find that react-burger-menu was the largest module in our build, even bigger than React.

The main culprit here is the **snapsvg** library, which contributes to %77 of the react-burger-menu size. I thought that was strange and wondered why an svg library was needed when I was using a simple slide menu.

I dug in and found that all the menu's in react-burger-menu are generated using the **menuFactory**. This menu factory implements [componentDidUpdate](https://github.com/negomi/react-burger-menu/blob/master/src/menuFactory.js#L151). `componentDidUpdate` is the only spot where snapsvg is used, and it only runs for the menu's who's styles object has the **svg** property.

This means that when I include the **push** menu into my project, it comes with the `componentDidUpdate` function, but the body of that function will never execute because **styles.svg** isn't defined. Additionally it brings in snapsvg, which really bloats our app.

I've put together a crude PR that suggests one possible way this could be avoided. There are most likely cleaner approaches, but I mainly wanted to raise this issue.

After splitting the one factory into a `baseMenuFactory` and an `svgAnimateMenuFactory` we see some pretty big size savings in our final app build:

screen shot 2016-06-29 at 10 28 10 am

react-burger-menu goes from taking up %20 of our total app size to only %5

### CODE REVIEW

**Comment by MikeKlemarewski** [comment]
Gah, realized I forgot to pull in the latest remote changes before opening this PR. I don't have time to fix it at the moment, but I don't really expect this PR to get merged as is. It's more to illustrate the issue, and provide one potential solution.

**Comment by negomi** [comment]
Hey @MikeKlemarewski, thanks for raising this - I wasn't aware how much bloat Snap.svg was bringing to the package, but it's definitely something I'd like to fix.

I'm going to play with a couple of different approaches, but either way, you're totally right that it makes no sense to include a bulky library in cases where it's not being used :)

**Comment by negomi** [comment]
Hi @MikeKlemarewski,

So I think we can achieve the same thing by requiring Snap.svg only in the files of the animations that actually use it, and then passing it to `menuFactory` along with their styles (see https://github.com/negomi/react-burger-menu/commit/66388f57fd331df7e4fd62af94c89c854dcf0872).

This approach requires minimal code changes but should mean the non-SVG animations will avoid pulling in that library.

Thanks again for your PR, and for letting me know about this issue!

**Comment by MikeKlemarewski** [comment]
Tested it out, works perfectly! Great solution 🎊

**Pull request closed without merging**
