### PR TITLE
Add CSS3 'transform' vendor prefixes for Webkit browsers.

### PR DESCRIPTION
**Pull request by patferguson**
This fixes the display of the off-canvas content on Webkit-based browsers such as iOS Safari.

I wasn't sure how you wanted to handle the built files so I left them as a separate commit, please let me know if you would like the commit prepared in another way.

### CODE REVIEW

**Comment by negomi** [comment]
Hi @patferguson, thanks for the PR!

Couple of questions:

* What's the issue with off-canvas content in Webkit browsers? The demo page seems to work on iOS Safari, so I wasn't aware of anything wrong. Do let me know if there's a bug :)
* Vendor prefixing should be handled automatically by [Radium](https://github.com/FormidableLabs/radium). I use that to avoid having to litter the code with `Webkit*` prefixes manually, so if they're not being applied where they should be, I'd be keen to investigate why Radium's not adding them first.

**Comment by patferguson** [comment]
Hi @negomi,

I observed that iPad Safari and Chrome were completely ignoring the transform style set by this library. The burger menu would start stuck open and the close button would get stuck slightly off screen. Desktop Chrome and Android Chrome worked flawlessly.

Sadly I didn't think to do a remote debug of the iPad I was testing with to see exactly what styles were being applied. However, applying the changes in this PR fixed the behaviour, does Radium require any special configuration for this? I haven't used it before.

Admittedly I was under a pretty tight deadline with this project so may have not set everything up correctly. Feel free to close this PR if you can't reproduce the issue.

**Comment by negomi** [comment]
I have just released v2.0.0, which removes Radium, and implements the changes here (plus other vendor prefixes) :)

Thanks again for your suggestion, sorry it's taken me so long to do anything about it!

**Comment by patferguson** [comment]
No worries, thanks for taking the time to let me know :)

**Pull request closed without merging**
