### PR TITLE
allow passing of custom listen for close handler

### PR DESCRIPTION
**Pull request by danReynolds**
Nothing big here, I needed to override the escape key `listenForClose` method and forked it with this change. If it is something you think adds value in this or some similar form I can do that change. Let me know, thanks!

### CODE REVIEW

**Comment by negomi** [comment]
Hey @danReynolds, thanks for this!

I'm curious what your use case was - did you just want to disable the close-on-Escape behavior? If so, I'm wondering if a more specific `disableCloseOnEsc` prop might be simpler for people to grasp.

We already have `onStateChange` which accepts a function to be called on open/close, and it seems like (with the exception of disabling the Esc key), this could be used for other things you might want to do in a custom `listenForClose` callback.

**Comment by danReynolds** [comment]
@negomi That's correct, my use case was just that I wanted it disabled. A disable prop also works, I'd be happy to make that change

**Comment by negomi** [comment]
That sounds great, I'd happily accept a PR for that.

**Comment by negomi** [comment]
I found some time to implement the `disableCloseOnEsc` prop, so it's now available (in v2.3.0).

See https://github.com/negomi/react-burger-menu#close-on-escape for more info.

Thanks for raising this issue!

**Pull request closed without merging**
