### PR TITLE
External control over isOpen value

### PR DESCRIPTION
**Pull request by orkisz**
We use version 1.1.6 due to React 0.13.3 dependency. We faced an issue that we need to control ``isOpen`` property externally. I updated component to check whether ``isOpen`` property passed from parent is ValueLink and use it, otherwise stay with state.

### CODE REVIEW

**Comment by negomi** [comment]
Hi @orkisz, thanks! I think this could be a useful feature, and I'll look at merging it into the next release :)

**Comment by flucivja** [comment]
Hi @orkisz, could you please merge this soon. This is must have feature which allows us to hide menu once user clicks to some link in it. Without it I am not sure how to do it without any dirty hacks. Thanks.

**Comment by orkisz** [comment]
Hi @flucivja, see https://github.com/negomi/react-burger-menu/pull/19. Waiting for response from @negomi

**Comment by negomi** [comment]
Fixed, see #19

**Pull request closed without merging**
