### PR TITLE
Add top/bottom positions including animations 

### PR DESCRIPTION
**Pull request by costagolub**
#167
Have added top and bottom positions including all animations except bubble and elastic. Those ones need still to be changed and I think it requires direct changes with the path so it's will not be possible to change via plain CSS.   
Thanks!

### CODE REVIEW

**Comment by mihailgaberov** [comment]
Hi guys, is this going to be merged soon?

**Comment by negomi** [comment]
I'm sorry I didn't get around to responding to this PR - I think it needs a little more work before merging:

1. Bubble and Elastic functionality as mentioned
2. A new example menu with the items positioned horizontally (the current ones make the menu taller than it feels like it should be for top/bottom positioning, and cause scrolling)

**Comment by b3e** [comment]
can this be merged?

**Comment by amarmechai** [comment]
Hi, when will this be merged?

**Comment by negomi** [comment]
@amarmechai see above ^

**Pull request closed without merging**
